-- MySQL Script generated by MySQL Workbench
-- lun 10 abr 2017 23:39:54 COT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema realtimechat
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `realtimechat` ;

-- -----------------------------------------------------
-- Schema realtimechat
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `realtimechat` DEFAULT CHARACTER SET utf8 ;
USE `realtimechat` ;

-- -----------------------------------------------------
-- Table `realtimechat`.`Usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `realtimechat`.`Usuarios` ;

CREATE TABLE IF NOT EXISTS `realtimechat`.`Usuarios` (
  `idUsuarios` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(70) NOT NULL,
  `Contraseña` VARCHAR(15) NOT NULL,
  `Correo` VARCHAR(70) NOT NULL,
  `Telefono` VARCHAR(11) NOT NULL,
  `Usuario` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idUsuarios`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
